### ISSUE TITLE
Questions About How to Reproduce Bugs

### ISSUE THREAD

**Issue by youzi27** [comsec-group/cascade-artifacts#12]
Hi @flaviens , 

Thank you very much for your work and the spirit of open source.

However, I am confused about how to reproduce the bugs mentioned in the paper. How can I reproduce the bugs detected in the paper? I have run **cva6** and **boom** for about 72 hours,  and there were no additional notifications on the console. The specific command parameters are: `python3 do_fuzzdesign.py cva6 10 0 1 0` and `python3 do_fuzzdesign.py boom 6 0 1 0`.
 
If I have missed any implementation details, please let me know. Thank you very much!

**Comment by asierfdln** [comment]
If I am not mistaken, those CPU designs you are trying out are the already-patched versions of the CPUs. Inside the Docker image, there are other directories in `/` like `cascade-cva6-c1/` or `cascade-kronos-k1/` such that `-c1` and `-k1` correspond to the bug identifier specified in the bug report table at the end of the paper.

**Comment by youzi27** [comment]
Thanks for clarifying.
