### ISSUE TITLE
Error regarding potentially insufficient UIDs or GIDs when running Docker

### ISSUE THREAD

**Issue by brightpeng** [comsec-group/cascade-artifacts#2]
When trying to pull a Docker container, I'm encountering the following error:

Error: writing blob: adding layer with blob "sha256:707e32e9fc569fee476af9e92ae3d1df8b8e6dca47f9cb31db9d2c922a6de952":
Error processing tar file(exit status 1): potentially insufficient UIDs or GIDs available in user namespace (requested 0:42 for /etc/gshadow): 
Check /etc/subuid and /etc/subgid: lchown /etc/gshadow: invalid argument

To address this, I have adjusted the ranges in both /etc/subuid and /etc/subgid multiple times. My current setting is:

[user_name]:100000:800000

However, the error persists.

Questions:

What should the correct UID and GID settings be to resolve this error?
Are there other potential settings or configurations that might be causing this issue?

Any guidance or recommendations would be greatly appreciated.

**Comment by flaviens** [comment]
Hi @brightpeng, thank you for reaching out! I'm not familiar with this issue but it _seems_ to be a Docker issue, unrelated with Cascade. Have you tried pulling something else to see if that would work?

**Comment by brightpeng** [comment]
Thanks! Let me keep trying. I just added sudo at the beginning of the
command line. Seemed working.

It now shows an error out of space though. Umm, the docker image seemed
big...

**Comment by flaviens** [comment]
Yes the image requires a couple of tens of GB. Alternatively I'd suggest you to reduce the Dockerfile (e.g. not do all the experiments and not clone all the designs) and start from there. In the end, the fuzzer itself is not especially big.
I'll close the issue. Please feel free to reopen if you have any concerns. Thanks!
