### ISSUE TITLE
How to Locate ELF Files for Analysis in Docker Environment?

### ISSUE THREAD

**Issue by brightpeng** [comsec-group/cascade-artifacts#3]
Hello,

I have successfully started the Docker container and am exploring its functionalities.

I noticed a command in the Docker setup:

RUN bash -c "source /cascade-meta/env.sh && cd /cascade-meta/fuzzer && python3 -u do_analyze_cascade_elfs.py"

This command seems to analyze ELF files, but I am unsure how to locate these ELF files within the Docker environment. Could you please guide me on where to find these ELF files, or how to generate them if they are not readily available?

Thank you for your time and for the great work on this project.

**Comment by flaviens** [comment]
Hi @brightpeng, thank you for reaching out! 

The path is defined in `do_analyze_cascade_elfs.py`:
```
gen_many_elfs('rocket', num_cores_for_elf_generation, NUM_ELFS, os.path.join(PATH_TO_TMP, 'manyelfs'))
```

And `PATH_TO_TMP` is defined in `runparams.py`
```
PATH_TO_TMP = os.path.join(os.environ['CASCADE_DATADIR'])
```

And this environment variable is defined in `cascade-meta/env.sh`, which you are encouraged to adapt according to your system.
Hope it helps!
