### ISSUE TITLE
Inquiry of the rough fuzzer time

### ISSUE THREAD

**Issue by brightpeng** [comsec-group/cascade-artifacts#5]
I wonder roughly how long it takes for running the fuzzer for a core? Is there a sign of finish?

I am current running `python3 do_fuzzdesign.py picorv32 30 100 1 0`

It has been running over 10 hours. ( I assigned 30 cores for the fuzzer. My system is Intel(R) Core(TM) i9-10980XE CPU @ 3.00GHz 36 cores.)

Still showing the following message.
/cascade-picorv32/cascade
Starting parallel testing of picorv32 on 30 processes.

The system still seemed busy when I run 'top' to check the core usage. Debating whether I should interrupt or not. Hope to check with you with the sign of finish.

**Comment by flaviens** [comment]
Hi @brightpeng, thank you for your message! The output of the fuzzer is the expected (probably PicoRV32 is clear of bugs that can be found by Cascade's current implementation). There is no clear and fundamental "finish" condition for Cascade. You may limit it by limiting its duration (e.g., be happy after N hours without bugs) or limiting the number of programs (e.g., you are happy after M programs without bugs). Please keep in mind that Cascade aims for practicality but not for exhaustivity.
Hope it answers!
